### ISSUE TITLE
Video showing it working

### ISSUE THREAD

**Issue by brunobasto** [Mecan0/Cyclone-with-leadscrews#1]
Hello! First of all, congratulations on the initiative of putting out a repository with this improvement to the Cyclone. Can I ask you how is the machine working for you? Do you use it often? Can you etch SMD traces? Can you provide a video?

Thanks!

**Comment by Mecan0** [comment]
https://www.youtube.com/watch?v=-G_8nDOv8zY

I don't use it often, I am focusing on give it a great rigidity.
